// Interactive Multi-Agent Supplier Negotiation Simulation Engine

export const NEGOTIATION_SUPPLIERS = [
  {
    id: "sup-phoenix-semi",
    name: "Apex Silicon Solutions (USA)",
    repName: "Sarah Jenkins",
    repRole: "VP of Strategic Enterprise Accounts",
    repAvatar: "SJ",
    reliabilityScore: 94,
    historicalConsignments: 680,
    onTimeRate: 97.8,
    defectRate: 0.04,
    isoStatus: "ISO 9001 & AS9100D Certified",
    initialOffer: {
      capacityUnits: 35000,
      unitPriceINR: 5200,
      baselinePriceINR: 4850,
      leadTimeDays: 10,
      rushSurchargePct: 15,
      minimumContractMonths: 3,
    },
    negotiatedOffer: {
      capacityUnits: 45000,
      unitPriceINR: 4950,
      leadTimeDays: 4,
      rushSurchargePct: 4,
      minimumContractMonths: 6,
      estimatedCostSavingsCr: 1.15,
    },
    dialogueRounds: [
      // Round 1
      [
        {
          id: "msg-1",
          round: 1,
          speaker: "supplier",
          speakerName: "Sarah Jenkins (Apex Silicon)",
          avatar: "SJ",
          timestamp: "10:14:02 AM",
          message: "Hello AURA Procurement Team. We received your urgent request for 35,000 SoC assemblies. Due to high fab load in Phoenix, our expedited quote is ₹5,200/unit with a 10-day dispatch lead time and 15% emergency rush allocation fee.",
          tag: "Initial Opening Offer",
          metrics: { price: "₹5,200", leadTime: "10 Days", capacity: "35k units" },
        },
        {
          id: "msg-2",
          round: 1,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Procurement Agent",
          avatar: "NX",
          timestamp: "10:14:15 AM",
          message: "Acknowledged, Sarah. However, our production models require delivery in Chennai within 4 days to avoid factory line-stop penalties. In exchange, AURA is willing to offer an exclusive 6-month dual-sourcing volume commitment of 45,000 units/month and 30-day accelerated payment terms. Can Apex Silicon reallocate Phoenix Line 4 and absorb the rush premium?",
          tag: "Counter-Proposal with Volume Incentive",
          metrics: { proposedPrice: "₹4,900", requestedLeadTime: "4 Days", volumeCommitment: "45k units/mo" },
        },
        {
          id: "msg-3",
          round: 1,
          speaker: "supplier",
          speakerName: "Sarah Jenkins (Apex Silicon)",
          avatar: "SJ",
          timestamp: "10:14:38 AM",
          message: "A 6-month guaranteed volume commitment changes the unit economics significantly for our executive committee. If AURA commits to 45,000 units/month for two quarters, we will waive 75% of the rush surcharge, adjust the unit price to ₹4,950, and prioritize your batch on Phoenix Line 4 for 4-day airlift dispatch.",
          tag: "Concession & Revised Term Sheet",
          metrics: { price: "₹4,950", leadTime: "4 Days", capacity: "45k units" },
        },
        {
          id: "msg-4",
          round: 1,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Procurement Agent",
          avatar: "NX",
          timestamp: "10:14:52 AM",
          message: "Terms evaluated: Net savings of ₹1.15 Cr compared to spot market rates. Recovery timeline reduced by 6 days. Risk confidence is 94%. Ready for executive decision.",
          tag: "Round 1 Milestone Reached",
          metrics: { status: "PROPOSAL READY", totalSavings: "₹1.15 Cr", recoveryDays: "4 Days" },
          offerUpdate: {
            capacityUnits: 45000,
            unitPriceINR: 4950,
            leadTimeDays: 4,
            rushSurchargePct: 4,
            minimumContractMonths: 6,
            estimatedCostSavingsCr: 1.15,
          }
        },
      ],
      // Round 2
      [
        {
          id: "msg-5",
          round: 2,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Procurement Agent",
          avatar: "NX",
          timestamp: "10:15:10 AM",
          message: "Sarah, our executive procurement committee reviewed the ₹4,950 quote. To finalize immediately, we require the remaining 4% rush surcharge completely eliminated (0%) and a unit price of ₹4,890. In exchange, AURA will expand the preferred vendor agreement across our Austin and Penang facilities.",
          tag: "Tougher Counter: Multi-Site Expansion",
          metrics: { proposedPrice: "₹4,890", surcharge: "0%", sites: "Austin + Penang + Chennai" },
        },
        {
          id: "msg-6",
          round: 2,
          speaker: "supplier",
          speakerName: "Sarah Jenkins (Apex Silicon)",
          avatar: "SJ",
          timestamp: "10:15:35 AM",
          message: "We conferred with our global fab operations committee. For multi-site preferred vendor status across 3 plants, Apex Silicon will eliminate 100% of rush surcharges (0%), reduce unit price to ₹4,890, and guarantee 3-day express air freight directly to Chennai.",
          tag: "Major Concession: 0% Surcharge",
          metrics: { price: "₹4,890", leadTime: "3 Days", surcharge: "0%" },
        },
        {
          id: "msg-7",
          round: 2,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Procurement Agent",
          avatar: "NX",
          timestamp: "10:15:48 AM",
          message: "Updated terms evaluated: Net savings increased to ₹1.42 Cr! Lead time compressed to 3 days. Ready for executive decision.",
          tag: "Round 2 Milestone Reached",
          metrics: { status: "DEEPER CONCESSION", totalSavings: "₹1.42 Cr", recoveryDays: "3 Days" },
          offerUpdate: {
            capacityUnits: 50000,
            unitPriceINR: 4890,
            leadTimeDays: 3,
            rushSurchargePct: 0,
            minimumContractMonths: 9,
            estimatedCostSavingsCr: 1.42,
          }
        },
      ],
      // Round 3
      [
        {
          id: "msg-8",
          round: 3,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Procurement Agent",
          avatar: "NX",
          timestamp: "10:16:02 AM",
          message: "One final stipulation before signature: AURA requires a 365-day zero-defect warranty guarantee and 10,000 units of consignment inventory buffer held in Singapore Hub at zero storage cost.",
          tag: "Final Strategic Clause Request",
          metrics: { warranty: "365 Days", consignment: "10k units buffer" },
        },
        {
          id: "msg-9",
          round: 3,
          speaker: "supplier",
          speakerName: "Sarah Jenkins (Apex Silicon)",
          avatar: "SJ",
          timestamp: "10:16:25 AM",
          message: "Deal accepted by Apex Executive Board! Final contract terms: ₹4,850/unit, 3-day dock delivery, 0% surcharge, 365-day warranty replacement, and 10,000 consignment units staged in Singapore. This is our absolute best-and-final offer.",
          tag: "Best & Final Offer Locked",
          metrics: { price: "₹4,850", leadTime: "3 Days", warranty: "365 Days", totalSavings: "₹1.65 Cr" },
        },
        {
          id: "msg-10",
          round: 3,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Procurement Agent",
          avatar: "NX",
          timestamp: "10:16:40 AM",
          message: "Maximum negotiation ceiling achieved: Net savings of ₹1.65 Cr. Lead time reduced by 70%. All penalty clauses mitigated.",
          tag: "Optimal Consensus Reached",
          metrics: { status: "OPTIMAL DEAL", totalSavings: "₹1.65 Cr", recoveryDays: "3 Days" },
          offerUpdate: {
            capacityUnits: 50000,
            unitPriceINR: 4850,
            leadTimeDays: 3,
            rushSurchargePct: 0,
            minimumContractMonths: 12,
            estimatedCostSavingsCr: 1.65,
          }
        },
      ]
    ],
    dialogueScript: [
      {
        id: "msg-1",
        round: 1,
        speaker: "supplier",
        speakerName: "Sarah Jenkins (Apex Silicon)",
        avatar: "SJ",
        timestamp: "10:14:02 AM",
        message: "Hello AURA Procurement Team. We received your urgent request for 35,000 SoC assemblies. Due to high fab load in Phoenix, our expedited quote is ₹5,200/unit with a 10-day dispatch lead time and 15% emergency rush allocation fee.",
        tag: "Initial Opening Offer",
        metrics: { price: "₹5,200", leadTime: "10 Days", capacity: "35k units" },
      },
      {
        id: "msg-2",
        round: 1,
        speaker: "nexus-agent",
        speakerName: "NEXUS Autonomous Procurement Agent",
        avatar: "NX",
        timestamp: "10:14:15 AM",
        message: "Acknowledged, Sarah. However, our production models require delivery in Chennai within 4 days to avoid factory line-stop penalties. In exchange, AURA is willing to offer an exclusive 6-month dual-sourcing volume commitment of 45,000 units/month and 30-day accelerated payment terms. Can Apex Silicon reallocate Phoenix Line 4 and absorb the rush premium?",
        tag: "Counter-Proposal with Volume Incentive",
        metrics: { proposedPrice: "₹4,900", requestedLeadTime: "4 Days", volumeCommitment: "45k units/mo" },
      },
      {
        id: "msg-3",
        round: 1,
        speaker: "supplier",
        speakerName: "Sarah Jenkins (Apex Silicon)",
        avatar: "SJ",
        timestamp: "10:14:38 AM",
        message: "A 6-month guaranteed volume commitment changes the unit economics significantly for our executive committee. If AURA commits to 45,000 units/month for two quarters, we will waive 75% of the rush surcharge, adjust the unit price to ₹4,950, and prioritize your batch on Phoenix Line 4 for 4-day airlift dispatch.",
        tag: "Concession & Revised Term Sheet",
        metrics: { price: "₹4,950", leadTime: "4 Days", capacity: "45k units" },
      },
      {
        id: "msg-4",
        round: 1,
        speaker: "nexus-agent",
        speakerName: "NEXUS Autonomous Procurement Agent",
        avatar: "NX",
        timestamp: "10:14:52 AM",
        message: "Terms evaluated: Net savings of ₹1.15 Cr compared to spot market rates. Recovery timeline reduced by 6 days. Risk confidence is 94%. Ready for executive decision.",
        tag: "Round 1 Milestone Reached",
        metrics: { status: "PROPOSAL READY", totalSavings: "₹1.15 Cr", recoveryDays: "4 Days" },
      },
    ],
  },
  {
    id: "sup-kyoto-ceramic",
    name: "Kyoto Microelectronics Corp (Japan)",
    repName: "Kenji Sato",
    repRole: "Director of International Operations",
    repAvatar: "KS",
    reliabilityScore: 99,
    historicalConsignments: 1180,
    onTimeRate: 99.4,
    defectRate: 0.01,
    isoStatus: "IATF 16949 & JIS Q 9100 Certified",
    initialOffer: {
      capacityUnits: 30000,
      unitPriceINR: 4750,
      baselinePriceINR: 4550,
      leadTimeDays: 8,
      rushSurchargePct: 8,
      minimumContractMonths: 3,
    },
    negotiatedOffer: {
      capacityUnits: 40000,
      unitPriceINR: 4620,
      leadTimeDays: 3,
      rushSurchargePct: 2,
      minimumContractMonths: 4,
      estimatedCostSavingsCr: 0.85,
    },
    dialogueRounds: [
      // Round 1
      [
        {
          id: "msg-1",
          round: 1,
          speaker: "supplier",
          speakerName: "Kenji Sato (Kyoto Micro)",
          avatar: "KS",
          timestamp: "10:20:10 AM",
          message: "Konnichiwa AURA team. We can allocate 30,000 substrate units from our Kansai facility. Standard quote is ₹4,750/unit with 8 days transit via ocean-air combo.",
          tag: "Opening Offer",
          metrics: { price: "₹4,750", leadTime: "8 Days", capacity: "30k units" },
        },
        {
          id: "msg-2",
          round: 1,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Procurement Agent",
          avatar: "NX",
          timestamp: "10:20:25 AM",
          message: "Kenji-san, we value our long-standing partnership. If Kyoto can compress transit to 3 days using direct Osaka-Chennai air cargo and increase batch size to 40,000 units, we will extend your Master Service Agreement by 4 quarters.",
          tag: "Strategic Partnership Counter",
          metrics: { proposedPrice: "₹4,600", requestedLeadTime: "3 Days", batch: "40k units" },
        },
        {
          id: "msg-3",
          round: 1,
          speaker: "supplier",
          speakerName: "Kenji Sato (Kyoto Micro)",
          avatar: "KS",
          timestamp: "10:20:45 AM",
          message: "Agreed. We will authorize direct pallet loading onto tomorrow's ANA cargo flight. Price finalized at ₹4,620/unit with 3-day dock delivery in Chennai.",
          tag: "MOU Finalized",
          metrics: { price: "₹4,620", leadTime: "3 Days", capacity: "40k units" },
        },
        {
          id: "msg-4",
          round: 1,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Procurement Agent",
          avatar: "NX",
          timestamp: "10:20:58 AM",
          message: "Terms evaluated: Net savings of ₹0.85 Cr, 3-day lead time achieved. Ready for executive decision.",
          tag: "Round 1 Milestone Reached",
          metrics: { status: "PROPOSAL READY", totalSavings: "₹0.85 Cr" },
        },
      ],
      // Round 2
      [
        {
          id: "msg-5",
          round: 2,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Procurement Agent",
          avatar: "NX",
          timestamp: "10:21:15 AM",
          message: "Kenji-san, can Kyoto provide split-shipment directly to Chennai and Penang concurrently, and lower unit pricing to ₹4,550 with Net-45 payment terms?",
          tag: "Split-Shipment Counter",
          metrics: { proposedPrice: "₹4,550", destination: "Chennai + Penang" },
        },
        {
          id: "msg-6",
          round: 2,
          speaker: "supplier",
          speakerName: "Kenji Sato (Kyoto Micro)",
          avatar: "KS",
          timestamp: "10:21:38 AM",
          message: "We can execute dual simultaneous air shipments to Chennai and Penang via Osaka-Kuala Lumpur and Osaka-Chennai at ₹4,560/unit with Net-45 terms.",
          tag: "Dual-Route Air Concession",
          metrics: { price: "₹4,560", leadTime: "2.5 Days", totalSavings: "₹1.10 Cr" },
        },
        {
          id: "msg-7",
          round: 2,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Procurement Agent",
          avatar: "NX",
          timestamp: "10:21:50 AM",
          message: "Dual-route agreement finalized: Net savings ₹1.10 Cr. Lead time 2.5 days. Ready for executive decision.",
          tag: "Round 2 Milestone Reached",
          metrics: { status: "DEEPER CONCESSION", totalSavings: "₹1.10 Cr" },
          offerUpdate: {
            capacityUnits: 45000,
            unitPriceINR: 4560,
            leadTimeDays: 2.5,
            rushSurchargePct: 0,
            minimumContractMonths: 6,
            estimatedCostSavingsCr: 1.10,
          }
        },
      ]
    ],
    dialogueScript: [
      {
        id: "msg-1",
        round: 1,
        speaker: "supplier",
        speakerName: "Kenji Sato (Kyoto Micro)",
        avatar: "KS",
        timestamp: "10:20:10 AM",
        message: "Konnichiwa AURA team. We can allocate 30,000 substrate units from our Kansai facility. Standard quote is ₹4,750/unit with 8 days transit via ocean-air combo.",
        tag: "Opening Offer",
        metrics: { price: "₹4,750", leadTime: "8 Days", capacity: "30k units" },
      },
      {
        id: "msg-2",
        round: 1,
        speaker: "nexus-agent",
        speakerName: "NEXUS Autonomous Procurement Agent",
        avatar: "NX",
        timestamp: "10:20:25 AM",
        message: "Kenji-san, we value our long-standing partnership. If Kyoto can compress transit to 3 days using direct Osaka-Chennai air cargo and increase batch size to 40,000 units, we will extend your Master Service Agreement by 4 quarters.",
        tag: "Strategic Partnership Counter",
        metrics: { proposedPrice: "₹4,600", requestedLeadTime: "3 Days", batch: "40k units" },
      },
      {
        id: "msg-3",
        round: 1,
        speaker: "supplier",
        speakerName: "Kenji Sato (Kyoto Micro)",
        avatar: "KS",
        timestamp: "10:20:45 AM",
        message: "Agreed. We will authorize direct pallet loading onto tomorrow's ANA cargo flight. Price finalized at ₹4,620/unit with 3-day dock delivery in Chennai.",
        tag: "MOU Finalized",
        metrics: { price: "₹4,620", leadTime: "3 Days", capacity: "40k units" },
      },
      {
        id: "msg-4",
        round: 1,
        speaker: "nexus-agent",
        speakerName: "NEXUS Autonomous Procurement Agent",
        avatar: "NX",
        timestamp: "10:20:58 AM",
        message: "Terms evaluated: Net savings of ₹0.85 Cr, 3-day lead time achieved. Ready for executive decision.",
        tag: "Round 1 Milestone Reached",
        metrics: { status: "PROPOSAL READY", totalSavings: "₹0.85 Cr" },
      },
    ],
  },
  {
    id: "sup-munich-sensors",
    name: "Bavaria Sensorik GmbH (Germany)",
    repName: "Dr. Elena Weber",
    repRole: "Chief Supply Officer",
    repAvatar: "EW",
    reliabilityScore: 96,
    historicalConsignments: 940,
    onTimeRate: 98.6,
    defectRate: 0.02,
    isoStatus: "ISO 14001 & VDA 6.3 Certified",
    initialOffer: {
      capacityUnits: 25000,
      unitPriceINR: 5100,
      baselinePriceINR: 4900,
      leadTimeDays: 12,
      rushSurchargePct: 12,
      minimumContractMonths: 3,
    },
    negotiatedOffer: {
      capacityUnits: 35000,
      unitPriceINR: 4880,
      leadTimeDays: 4,
      rushSurchargePct: 0,
      minimumContractMonths: 6,
      estimatedCostSavingsCr: 1.28,
    },
    dialogueRounds: [
      // Round 1
      [
        {
          id: "msg-1",
          round: 1,
          speaker: "supplier",
          speakerName: "Dr. Elena Weber (Bavaria Sensorik)",
          avatar: "EW",
          timestamp: "10:25:05 AM",
          message: "Guten Tag AURA colleagues. Our Munich fabrication lines are operating at 68% utilization. We can immediately spool up 25,000 MEMS sensors at ₹5,100/unit with 12 days standard Lufthansa cargo routing.",
          tag: "Opening Offer",
          metrics: { price: "₹5,100", leadTime: "12 Days", capacity: "25k units" },
        },
        {
          id: "msg-2",
          round: 1,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Procurement Agent",
          avatar: "NX",
          timestamp: "10:25:22 AM",
          message: "Dr. Weber, our assembly hubs in Chennai and Penang cannot withstand a 12-day lag. We propose upgrading this to 35,000 units with expedited Frankfurt-Bengaluru express charter at ₹4,880/unit and 0% rush premium in return for a 2-year tier-1 sensor exclusivity agreement.",
          tag: "Volume & Exclusivity Bid",
          metrics: { proposedPrice: "₹4,880", requestedLeadTime: "4 Days", term: "2 Years" },
        },
        {
          id: "msg-3",
          round: 1,
          speaker: "supplier",
          speakerName: "Dr. Elena Weber (Bavaria Sensorik)",
          avatar: "EW",
          timestamp: "10:25:49 AM",
          message: "A 2-year preferred vendor partnership is very compelling for our supervisory board. Bavaria Sensorik approves ₹4,880/unit, 100% waiver of rush fees, and charter dispatch landing in Bengaluru in 4 calendar days.",
          tag: "Agreement Authorized",
          metrics: { price: "₹4,880", leadTime: "4 Days", capacity: "35k units" },
        },
        {
          id: "msg-4",
          round: 1,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Procurement Agent",
          avatar: "NX",
          timestamp: "10:26:01 AM",
          message: "European corridor secured: ₹1.28 Cr net cost avoidance, lead time compressed by 8 days. Ready for executive decision.",
          tag: "Round 1 Milestone Reached",
          metrics: { status: "PROPOSAL READY", totalSavings: "₹1.28 Cr", recoveryDays: "4 Days" },
          offerUpdate: {
            capacityUnits: 35000,
            unitPriceINR: 4880,
            leadTimeDays: 4,
            rushSurchargePct: 0,
            minimumContractMonths: 6,
            estimatedCostSavingsCr: 1.28,
          }
        },
      ]
    ],
    dialogueScript: [
      {
        id: "msg-1",
        round: 1,
        speaker: "supplier",
        speakerName: "Dr. Elena Weber (Bavaria Sensorik)",
        avatar: "EW",
        timestamp: "10:25:05 AM",
        message: "Guten Tag AURA colleagues. Our Munich fabrication lines are operating at 68% utilization. We can immediately spool up 25,000 MEMS sensors at ₹5,100/unit with 12 days standard Lufthansa cargo routing.",
        tag: "Opening Offer",
        metrics: { price: "₹5,100", leadTime: "12 Days", capacity: "25k units" },
      },
      {
        id: "msg-2",
        round: 1,
        speaker: "nexus-agent",
        speakerName: "NEXUS Autonomous Procurement Agent",
        avatar: "NX",
        timestamp: "10:25:22 AM",
        message: "Dr. Weber, our assembly hubs in Chennai and Penang cannot withstand a 12-day lag. We propose upgrading this to 35,000 units with expedited Frankfurt-Bengaluru express charter at ₹4,880/unit and 0% rush premium in return for a 2-year tier-1 sensor exclusivity agreement.",
        tag: "Volume & Exclusivity Bid",
        metrics: { proposedPrice: "₹4,880", requestedLeadTime: "4 Days", term: "2 Years" },
      },
      {
        id: "msg-3",
        round: 1,
        speaker: "supplier",
        speakerName: "Dr. Elena Weber (Bavaria Sensorik)",
        avatar: "EW",
        timestamp: "10:25:49 AM",
        message: "A 2-year preferred vendor partnership is very compelling for our supervisory board. Bavaria Sensorik approves ₹4,880/unit, 100% waiver of rush fees, and charter dispatch landing in Bengaluru in 4 calendar days.",
        tag: "Agreement Authorized",
        metrics: { price: "₹4,880", leadTime: "4 Days", capacity: "35k units" },
      },
      {
        id: "msg-4",
        round: 1,
        speaker: "nexus-agent",
        speakerName: "NEXUS Autonomous Procurement Agent",
        avatar: "NX",
        timestamp: "10:26:01 AM",
        message: "European corridor secured: ₹1.28 Cr net cost avoidance, lead time compressed by 8 days. Ready for executive decision.",
        tag: "Round 1 Milestone Reached",
        metrics: { status: "PROPOSAL READY", totalSavings: "₹1.28 Cr", recoveryDays: "4 Days" },
      },
    ],
  },
  {
    id: "sup-taiwan-semi",
    name: "Taiwan Micro Foundry (TSMC Partner)",
    repName: "Dr. Morris Lin",
    repRole: "VP Global Strategic Alliances",
    repAvatar: "ML",
    reliabilityScore: 98,
    historicalConsignments: 1420,
    onTimeRate: 99.2,
    defectRate: 0.015,
    isoStatus: "ISO 9001, IATF 16949 & TSMC Gold SLA",
    initialOffer: {
      capacityUnits: 60000,
      unitPriceINR: 4400,
      baselinePriceINR: 4200,
      leadTimeDays: 14,
      rushSurchargePct: 10,
      minimumContractMonths: 6,
    },
    negotiatedOffer: {
      capacityUnits: 80000,
      unitPriceINR: 4180,
      leadTimeDays: 5,
      rushSurchargePct: 0,
      minimumContractMonths: 12,
      estimatedCostSavingsCr: 2.10,
    },
    dialogueRounds: [
      // Round 1
      [
        {
          id: "msg-1",
          round: 1,
          speaker: "supplier",
          speakerName: "Dr. Morris Lin (Taiwan Micro)",
          avatar: "ML",
          timestamp: "10:30:10 AM",
          message: "Greetings AURA executive leadership. Following recent line disruptions, we can allocate 60,000 high-density 5nm SoC wafers from Fab 12 at ₹4,400/unit with a 14-day turnaround.",
          tag: "Primary Source Opening Offer",
          metrics: { price: "₹4,400", leadTime: "14 Days", capacity: "60k wafers" },
        },
        {
          id: "msg-2",
          round: 1,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Procurement Agent",
          avatar: "NX",
          timestamp: "10:30:28 AM",
          message: "Dr. Lin, to normalize supply chain throughput and absorb Taiwan backlog, AURA can lock in 80,000 units on a guaranteed 12-month contract at ₹4,180/unit with priority cleanroom staging in 5 days.",
          tag: "Enterprise Volume Anchor",
          metrics: { proposedPrice: "₹4,180", targetTime: "5 Days", volume: "80k units" },
        },
        {
          id: "msg-3",
          round: 1,
          speaker: "supplier",
          speakerName: "Dr. Morris Lin (Taiwan Micro)",
          avatar: "ML",
          timestamp: "10:30:52 AM",
          message: "Agreed. Given our decade-long strategic collaboration, Taiwan Micro Foundry authorizes Line 7 emergency batch run at ₹4,180/unit, zero rush fees, and expedited Taipei-Chennai air bridge delivery in 5 days.",
          tag: "Strategic Accord Reached",
          metrics: { price: "₹4,180", leadTime: "5 Days", capacity: "80k units" },
        },
        {
          id: "msg-4",
          round: 1,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Procurement Agent",
          avatar: "NX",
          timestamp: "10:31:05 AM",
          message: "Taiwan Foundry capacity normalized: ₹2.10 Cr in cost savings unlocked, 9-day lead time reduction. Ready for executive decision.",
          tag: "Round 1 Milestone Reached",
          metrics: { status: "PROPOSAL READY", totalSavings: "₹2.10 Cr", recoveryDays: "5 Days" },
          offerUpdate: {
            capacityUnits: 80000,
            unitPriceINR: 4180,
            leadTimeDays: 5,
            rushSurchargePct: 0,
            minimumContractMonths: 12,
            estimatedCostSavingsCr: 2.10,
          }
        },
      ]
    ],
    dialogueScript: [
      {
        id: "msg-1",
        round: 1,
        speaker: "supplier",
        speakerName: "Dr. Morris Lin (Taiwan Micro)",
        avatar: "ML",
        timestamp: "10:30:10 AM",
        message: "Greetings AURA executive leadership. Following recent line disruptions, we can allocate 60,000 high-density 5nm SoC wafers from Fab 12 at ₹4,400/unit with a 14-day turnaround.",
        tag: "Primary Source Opening Offer",
        metrics: { price: "₹4,400", leadTime: "14 Days", capacity: "60k wafers" },
      },
      {
        id: "msg-2",
        round: 1,
        speaker: "nexus-agent",
        speakerName: "NEXUS Autonomous Procurement Agent",
        avatar: "NX",
        timestamp: "10:30:28 AM",
        message: "Dr. Lin, to normalize supply chain throughput and absorb Taiwan backlog, AURA can lock in 80,000 units on a guaranteed 12-month contract at ₹4,180/unit with priority cleanroom staging in 5 days.",
        tag: "Enterprise Volume Anchor",
        metrics: { proposedPrice: "₹4,180", targetTime: "5 Days", volume: "80k units" },
      },
      {
        id: "msg-3",
        round: 1,
        speaker: "supplier",
        speakerName: "Dr. Morris Lin (Taiwan Micro)",
        avatar: "ML",
        timestamp: "10:30:52 AM",
        message: "Agreed. Given our decade-long strategic collaboration, Taiwan Micro Foundry authorizes Line 7 emergency batch run at ₹4,180/unit, zero rush fees, and expedited Taipei-Chennai air bridge delivery in 5 days.",
        tag: "Strategic Accord Reached",
        metrics: { price: "₹4,180", leadTime: "5 Days", capacity: "80k units" },
      },
      {
        id: "msg-4",
        round: 1,
        speaker: "nexus-agent",
        speakerName: "NEXUS Autonomous Procurement Agent",
        avatar: "NX",
        timestamp: "10:31:05 AM",
        message: "Taiwan Foundry capacity normalized: ₹2.10 Cr in cost savings unlocked, 9-day lead time reduction. Ready for executive decision.",
        tag: "Round 1 Milestone Reached",
        metrics: { status: "PROPOSAL READY", totalSavings: "₹2.10 Cr", recoveryDays: "5 Days" },
      },
    ],
  },
  {
    id: "sup-seoul-mem",
    name: "Han River Memory Semiconductor (Korea)",
    repName: "Min-Jun Park",
    repRole: "Global Distribution Director",
    repAvatar: "MP",
    reliabilityScore: 97,
    historicalConsignments: 1320,
    onTimeRate: 98.9,
    defectRate: 0.02,
    isoStatus: "ISO 9001 & KS Q 9100 Certified",
    initialOffer: {
      capacityUnits: 40000,
      unitPriceINR: 2450,
      baselinePriceINR: 2300,
      leadTimeDays: 9,
      rushSurchargePct: 9,
      minimumContractMonths: 4,
    },
    negotiatedOffer: {
      capacityUnits: 55000,
      unitPriceINR: 2280,
      leadTimeDays: 3,
      rushSurchargePct: 0,
      minimumContractMonths: 8,
      estimatedCostSavingsCr: 0.94,
    },
    dialogueRounds: [
      // Round 1
      [
        {
          id: "msg-1",
          round: 1,
          speaker: "supplier",
          speakerName: "Min-Jun Park (Han River Memory)",
          avatar: "MP",
          timestamp: "10:35:10 AM",
          message: "Annyeonghaseyo AURA. We have 40,000 LPDDR5 memory modules ready for immediate dispatch from Incheon Hub. Expedited spot quote is ₹2,450/unit with 9 days standard delivery.",
          tag: "Memory Opening Quote",
          metrics: { price: "₹2,450", leadTime: "9 Days", capacity: "40k units" },
        },
        {
          id: "msg-2",
          round: 1,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Procurement Agent",
          avatar: "NX",
          timestamp: "10:35:30 AM",
          message: "Min-Jun, AURA will commit to 55,000 memory units per month across all AuraX Pro production runs if Han River provides direct Asiana air courier delivery within 3 days at ₹2,280/unit.",
          tag: "Multi-Product Scaling Counter",
          metrics: { proposedPrice: "₹2,280", leadTime: "3 Days", volume: "55k units/mo" },
        },
        {
          id: "msg-3",
          round: 1,
          speaker: "supplier",
          speakerName: "Min-Jun Park (Han River Memory)",
          avatar: "MP",
          timestamp: "10:35:55 AM",
          message: "Confirmed and approved! Han River will dispatch via Seoul-Chennai dedicated cargo flight at ₹2,280/unit with 0% rush premium and 3-day arrival.",
          tag: "Accord Signed",
          metrics: { price: "₹2,280", leadTime: "3 Days", capacity: "55k units" },
        },
        {
          id: "msg-4",
          round: 1,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Procurement Agent",
          avatar: "NX",
          timestamp: "10:36:08 AM",
          message: "Memory subsystem secured: Net savings ₹0.94 Cr, 6-day lead time improvement. Ready for executive decision.",
          tag: "Round 1 Milestone Reached",
          metrics: { status: "PROPOSAL READY", totalSavings: "₹0.94 Cr", recoveryDays: "3 Days" },
          offerUpdate: {
            capacityUnits: 55000,
            unitPriceINR: 2280,
            leadTimeDays: 3,
            rushSurchargePct: 0,
            minimumContractMonths: 8,
            estimatedCostSavingsCr: 0.94,
          }
        },
      ]
    ],
    dialogueScript: [
      {
        id: "msg-1",
        round: 1,
        speaker: "supplier",
        speakerName: "Min-Jun Park (Han River Memory)",
        avatar: "MP",
        timestamp: "10:35:10 AM",
        message: "Annyeonghaseyo AURA. We have 40,000 LPDDR5 memory modules ready for immediate dispatch from Incheon Hub. Expedited spot quote is ₹2,450/unit with 9 days standard delivery.",
        tag: "Memory Opening Quote",
        metrics: { price: "₹2,450", leadTime: "9 Days", capacity: "40k units" },
      },
      {
        id: "msg-2",
        round: 1,
        speaker: "nexus-agent",
        speakerName: "NEXUS Autonomous Procurement Agent",
        avatar: "NX",
        timestamp: "10:35:30 AM",
        message: "Min-Jun, AURA will commit to 55,000 memory units per month across all AuraX Pro production runs if Han River provides direct Asiana air courier delivery within 3 days at ₹2,280/unit.",
        tag: "Multi-Product Scaling Counter",
        metrics: { proposedPrice: "₹2,280", leadTime: "3 Days", volume: "55k units/mo" },
      },
      {
        id: "msg-3",
        round: 1,
        speaker: "supplier",
        speakerName: "Min-Jun Park (Han River Memory)",
        avatar: "MP",
        timestamp: "10:35:55 AM",
        message: "Confirmed and approved! Han River will dispatch via Seoul-Chennai dedicated cargo flight at ₹2,280/unit with 0% rush premium and 3-day arrival.",
        tag: "Accord Signed",
        metrics: { price: "₹2,280", leadTime: "3 Days", capacity: "55k units" },
      },
      {
        id: "msg-4",
        round: 1,
        speaker: "nexus-agent",
        speakerName: "NEXUS Autonomous Procurement Agent",
        avatar: "NX",
        timestamp: "10:36:08 AM",
        message: "Memory subsystem secured: Net savings ₹0.94 Cr, 6-day lead time improvement. Ready for executive decision.",
        tag: "Round 1 Milestone Reached",
        metrics: { status: "PROPOSAL READY", totalSavings: "₹0.94 Cr", recoveryDays: "3 Days" },
      },
    ],
  },
];

export function getSupplierNegotiation(supplierId = "sup-phoenix-semi") {
  return NEGOTIATION_SUPPLIERS.find(s => s.id === supplierId) || NEGOTIATION_SUPPLIERS[0];
}
