// Interactive Multi-Agent Negotiation Simulation Engine for North Eastern Region (NER)
// Counterparts: NFR Railways, Border Roads Organisation (BRO), IWAI Waterways, IAF Air Command, IOCL North East

export const NEGOTIATION_SUPPLIERS = [
  {
    id: "sup-nfr-railway",
    name: "North East Frontier Railway (NFR Freight Directorate)",
    repName: "Sanjay K. Barua, IRTS",
    repRole: "Chief Freight Transportation Manager (Maligaon)",
    repAvatar: "SB",
    reliabilityScore: 98,
    historicalConsignments: 1420,
    onTimeRate: 98.4,
    defectRate: 0.02,
    isoStatus: "Indian Railways Core Freight SLA Certified",
    initialOffer: {
      capacityUnits: 38000,
      unitPriceINR: 1150,
      baselinePriceINR: 980,
      leadTimeDays: 5,
      rushSurchargePct: 18,
      minimumContractMonths: 3,
    },
    negotiatedOffer: {
      capacityUnits: 50000,
      unitPriceINR: 940,
      leadTimeDays: 2,
      rushSurchargePct: 0,
      minimumContractMonths: 6,
      estimatedCostSavingsCr: 1.45,
    },
    dialogueRounds: [
      // Round 1
      [
        {
          id: "msg-1",
          round: 1,
          speaker: "supplier",
          speakerName: "Sanjay K. Barua (NFR Maligaon)",
          avatar: "SB",
          timestamp: "10:14:02 AM",
          message: "Greetings MDoNER Command. We have reviewed your urgent requisition for 38,000 emergency consignment units. Given high traffic along the Guwahati-Lumding line, our expedited rake turnaround quote is ₹1,150/unit with a 5-day dispatch timeline and 18% special line-clearance fee.",
          tag: "Initial Freight Rake Proposal",
          metrics: { price: "₹1,150", leadTime: "5 Days", capacity: "38k units" },
        },
        {
          id: "msg-2",
          round: 1,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Inter-Agency Agent",
          avatar: "NX",
          timestamp: "10:14:15 AM",
          message: "Acknowledged, Shri Barua. However, the Sonapur landslide threatens critical hospital oxygen reserves in Agartala within 48 hours. In exchange for green-corridor Ro-Ro flat-car priority through Badarpur within 2 days, MDoNER guarantees a 6-month priority bulk allocation of 50,000 units/month with instant electronic treasury settlement. Can NFR waive the special clearance fee?",
          tag: "Counter-Proposal with Lifeline Protocol",
          metrics: { proposedPrice: "₹920", requestedLeadTime: "2 Days", volumeCommitment: "50k units/mo" },
        },
        {
          id: "msg-3",
          round: 1,
          speaker: "supplier",
          speakerName: "Sanjay K. Barua (NFR Maligaon)",
          avatar: "SB",
          timestamp: "10:14:38 AM",
          message: "Understood. The humanitarian priority of the Sonapur blockage is recognized by Railway Board. With the 6-month standing charter, NFR will waive 100% of the rush surcharge, adjust freight tariffs to ₹940/unit, and deploy 2 dedicated Ro-Ro trains with Green Corridor clearance arriving at Badarpur/Agartala within 48 hours.",
          tag: "Rake Allocation Accord Finalised",
          metrics: { price: "₹940", leadTime: "2 Days", capacity: "50k units" },
        },
        {
          id: "msg-4",
          round: 1,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Inter-Agency Agent",
          avatar: "NX",
          timestamp: "10:14:52 AM",
          message: "Terms evaluated: Net logistics savings of ₹1.45 Cr against spot road charter. Transit compressed by 3 days. Green corridor rail protocol locked. Ready for executive endorsement.",
          tag: "Round 1 Milestone Reached",
          metrics: { status: "PROPOSAL READY", totalSavings: "₹1.45 Cr", recoveryDays: "2 Days" },
          offerUpdate: {
            capacityUnits: 50000,
            unitPriceINR: 940,
            leadTimeDays: 2,
            rushSurchargePct: 0,
            minimumContractMonths: 6,
            estimatedCostSavingsCr: 1.45,
          }
        },
      ]
    ],
    dialogueScript: [
      {
        id: "msg-1",
        round: 1,
        speaker: "supplier",
        speakerName: "Sanjay K. Barua (NFR Maligaon)",
        avatar: "SB",
        timestamp: "10:14:02 AM",
        message: "Greetings MDoNER Command. We have reviewed your urgent requisition for 38,000 emergency consignment units. Given high traffic along the Guwahati-Lumding line, our expedited rake turnaround quote is ₹1,150/unit with a 5-day dispatch timeline and 18% special line-clearance fee.",
        tag: "Initial Freight Rake Proposal",
        metrics: { price: "₹1,150", leadTime: "5 Days", capacity: "38k units" },
      },
      {
        id: "msg-2",
        round: 1,
        speaker: "nexus-agent",
        speakerName: "NEXUS Autonomous Inter-Agency Agent",
        avatar: "NX",
        timestamp: "10:14:15 AM",
        message: "Acknowledged, Shri Barua. However, the Sonapur landslide threatens critical hospital oxygen reserves in Agartala within 48 hours. In exchange for green-corridor Ro-Ro flat-car priority through Badarpur within 2 days, MDoNER guarantees a 6-month priority bulk allocation of 50,000 units/month with instant electronic treasury settlement. Can NFR waive the special clearance fee?",
        tag: "Counter-Proposal with Lifeline Protocol",
        metrics: { proposedPrice: "₹920", requestedLeadTime: "2 Days", volumeCommitment: "50k units/mo" },
      },
      {
        id: "msg-3",
        round: 1,
        speaker: "supplier",
        speakerName: "Sanjay K. Barua (NFR Maligaon)",
        avatar: "SB",
        timestamp: "10:14:38 AM",
        message: "Understood. The humanitarian priority of the Sonapur blockage is recognized by Railway Board. With the 6-month standing charter, NFR will waive 100% of the rush surcharge, adjust freight tariffs to ₹940/unit, and deploy 2 dedicated Ro-Ro trains with Green Corridor clearance arriving at Badarpur/Agartala within 48 hours.",
        tag: "Rake Allocation Accord Finalised",
        metrics: { price: "₹940", leadTime: "2 Days", capacity: "50k units" },
      },
      {
        id: "msg-4",
        round: 1,
        speaker: "nexus-agent",
        speakerName: "NEXUS Autonomous Inter-Agency Agent",
        avatar: "NX",
        timestamp: "10:14:52 AM",
        message: "Terms evaluated: Net logistics savings of ₹1.45 Cr against spot road charter. Transit compressed by 3 days. Green corridor rail protocol locked. Ready for executive endorsement.",
        tag: "Round 1 Milestone Reached",
        metrics: { status: "PROPOSAL READY", totalSavings: "₹1.45 Cr", recoveryDays: "2 Days" },
      },
    ],
  },
  {
    id: "sup-bro-command",
    name: "Border Roads Organisation (Project Vartak & Pushpak)",
    repName: "Col. Vikramaditya Rathore",
    repRole: "Commander, 756 Border Road Task Force (BRTF)",
    repAvatar: "VR",
    reliabilityScore: 99,
    historicalConsignments: 890,
    onTimeRate: 99.1,
    defectRate: 0.01,
    isoStatus: "Military High-Altitude Engineering Certified",
    initialOffer: {
      capacityUnits: 30000,
      unitPriceINR: 1450,
      baselinePriceINR: 1200,
      leadTimeDays: 4,
      rushSurchargePct: 20,
      minimumContractMonths: 4,
    },
    negotiatedOffer: {
      capacityUnits: 40000,
      unitPriceINR: 1180,
      leadTimeDays: 1.5,
      rushSurchargePct: 0,
      minimumContractMonths: 6,
      estimatedCostSavingsCr: 1.28,
    },
    dialogueRounds: [
      [
        {
          id: "msg-1",
          round: 1,
          speaker: "supplier",
          speakerName: "Col. V. Rathore (BRO Task Force)",
          avatar: "VR",
          timestamp: "10:20:11 AM",
          message: "MDoNER Control, this is BRO Task Force Command at Sonapur. The debris flow covers 180 meters. Launching emergency Bailey bridge sections and clearing rockfall typically requires 96 hours with a ₹1,450/unit mobilization overhead.",
          tag: "Engineering Assessment",
          metrics: { price: "₹1,450", leadTime: "4 Days", clearanceCapacity: "30k units" },
        },
        {
          id: "msg-2",
          round: 1,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Inter-Agency Agent",
          avatar: "NX",
          timestamp: "10:20:30 AM",
          message: "Colonel Rathore, NEXUS models show medical hypoxia risk in Tripura hospitals if clearance takes 4 days. If BRO commits to a 36-hour dual-bank Bailey bridge launch with round-the-clock excavator relays, MDoNER releases ₹2.5 Cr emergency PM-DevINE civil works funding and priority heavy transport escort.",
          tag: "Tactical Acceleration Proposal",
          metrics: { proposedLeadTime: "1.5 Days", fundingClearance: "₹2.5 Cr" },
        },
        {
          id: "msg-3",
          round: 1,
          speaker: "supplier",
          speakerName: "Col. V. Rathore (BRO Task Force)",
          avatar: "VR",
          timestamp: "10:20:55 AM",
          message: "Approved. With PM-DevINE emergency fund authorization, Project Pushpak is deploying 4 heavy Komatsu excavators from Shillong and launching a double-single 120-ft Bailey bridge. Single-lane convoy passage will be operational within 36 hours at ₹1,180/unit with 0% surcharge.",
          tag: "Mission Acceptance",
          metrics: { price: "₹1,180", leadTime: "1.5 Days", capacity: "40k units" },
        },
        {
          id: "msg-4",
          round: 1,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Inter-Agency Agent",
          avatar: "NX",
          timestamp: "10:21:12 AM",
          message: "Corridor clearance accelerated by 60 hours. Estimated economic loss prevented: ₹1.28 Cr. Military convoy escort protocol verified.",
          tag: "Terms Locked",
          metrics: { status: "PROPOSAL READY", totalSavings: "₹1.28 Cr", recoveryDays: "1.5 Days" },
        },
      ]
    ],
    dialogueScript: [
      {
        id: "msg-1",
        round: 1,
        speaker: "supplier",
        speakerName: "Col. V. Rathore (BRO Task Force)",
        avatar: "VR",
        timestamp: "10:20:11 AM",
        message: "MDoNER Control, this is BRO Task Force Command at Sonapur. The debris flow covers 180 meters. Launching emergency Bailey bridge sections and clearing rockfall typically requires 96 hours with a ₹1,450/unit mobilization overhead.",
        tag: "Engineering Assessment",
        metrics: { price: "₹1,450", leadTime: "4 Days", clearanceCapacity: "30k units" },
      },
      {
        id: "msg-2",
        round: 1,
        speaker: "nexus-agent",
        speakerName: "NEXUS Autonomous Inter-Agency Agent",
        avatar: "NX",
        timestamp: "10:20:30 AM",
        message: "Colonel Rathore, NEXUS models show medical hypoxia risk in Tripura hospitals if clearance takes 4 days. If BRO commits to a 36-hour dual-bank Bailey bridge launch with round-the-clock excavator relays, MDoNER releases ₹2.5 Cr emergency PM-DevINE civil works funding and priority heavy transport escort.",
        tag: "Tactical Acceleration Proposal",
        metrics: { proposedLeadTime: "1.5 Days", fundingClearance: "₹2.5 Cr" },
      },
      {
        id: "msg-3",
        round: 1,
        speaker: "supplier",
        speakerName: "Col. V. Rathore (BRO Task Force)",
        avatar: "VR",
        timestamp: "10:20:55 AM",
        message: "Approved. With PM-DevINE emergency fund authorization, Project Pushpak is deploying 4 heavy Komatsu excavators from Shillong and launching a double-single 120-ft Bailey bridge. Single-lane convoy passage will be operational within 36 hours at ₹1,180/unit with 0% surcharge.",
        tag: "Mission Acceptance",
        metrics: { price: "₹1,180", leadTime: "1.5 Days", capacity: "40k units" },
      },
      {
        id: "msg-4",
        round: 1,
        speaker: "nexus-agent",
        speakerName: "NEXUS Autonomous Inter-Agency Agent",
        avatar: "NX",
        timestamp: "10:21:12 AM",
        message: "Corridor clearance accelerated by 60 hours. Estimated economic loss prevented: ₹1.28 Cr. Military convoy escort protocol verified.",
        tag: "Terms Locked",
        metrics: { status: "PROPOSAL READY", totalSavings: "₹1.28 Cr", recoveryDays: "1.5 Days" },
      },
    ],
  },
  {
    id: "sup-iwai-waterway",
    name: "Inland Waterways Authority of India (NW-2 Operations)",
    repName: "Pranab Bordoloi",
    repRole: "Regional Director (Pandu River Port)",
    repAvatar: "PB",
    reliabilityScore: 94,
    historicalConsignments: 520,
    onTimeRate: 96.2,
    defectRate: 0.03,
    isoStatus: "National Waterways Cargo Navigation Certified",
    initialOffer: {
      capacityUnits: 25000,
      unitPriceINR: 850,
      baselinePriceINR: 650,
      leadTimeDays: 4,
      rushSurchargePct: 25,
      minimumContractMonths: 3,
    },
    negotiatedOffer: {
      capacityUnits: 35000,
      unitPriceINR: 620,
      leadTimeDays: 2.2,
      rushSurchargePct: 0,
      minimumContractMonths: 6,
      estimatedCostSavingsCr: 0.88,
    },
    dialogueRounds: [
      [
        {
          id: "msg-1",
          round: 1,
          speaker: "supplier",
          speakerName: "Pranab Bordoloi (IWAI Pandu)",
          avatar: "PB",
          timestamp: "10:25:05 AM",
          message: "Namaskar MDoNER. IWAI has 3 self-propelled barges moored at Pandu Port. We can activate river transport to Dhubri and Jogighopa at ₹850/unit with 4-day turnaround.",
          tag: "River Transport Quote",
          metrics: { price: "₹850", leadTime: "4 Days", capacity: "25k units" },
        },
        {
          id: "msg-2",
          round: 1,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Inter-Agency Agent",
          avatar: "NX",
          timestamp: "10:25:22 AM",
          message: "Shri Bordoloi, we propose integrating NW-2 into the permanent MDoNER multimodal fallback charter. If IWAI mobilizes all 4 barges for continuous 24-hour night-navigation between Pandu and Dhubri, we lock a 6-month commitment at ₹620/unit.",
          tag: "Multi-Season River Charter",
          metrics: { proposedPrice: "₹620", requestedLeadTime: "2.2 Days", capacity: "35k units" },
        },
        {
          id: "msg-3",
          round: 1,
          speaker: "supplier",
          speakerName: "Pranab Bordoloi (IWAI Pandu)",
          avatar: "PB",
          timestamp: "10:25:48 AM",
          message: "Agreement confirmed. IWAI will activate night-navigational beacons along Sector 3 of the Brahmaputra. 4 barges carrying 35,000 emergency units will depart Pandu within 6 hours, arriving in Jogighopa in 2.2 days.",
          tag: "Waterway Fleet Deployed",
          metrics: { price: "₹620", leadTime: "2.2 Days", capacity: "35k units" },
        },
        {
          id: "msg-4",
          round: 1,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Inter-Agency Agent",
          avatar: "NX",
          timestamp: "10:26:01 AM",
          message: "Brahmaputra river failover activated. Net transport savings: ₹0.88 Cr. Zero carbon emission penalty.",
          tag: "Round Milestone Reached",
          metrics: { status: "PROPOSAL READY", totalSavings: "₹0.88 Cr", recoveryDays: "2.2 Days" },
        },
      ]
    ],
    dialogueScript: [
      {
        id: "msg-1",
        round: 1,
        speaker: "supplier",
        speakerName: "Pranab Bordoloi (IWAI Pandu)",
        avatar: "PB",
        timestamp: "10:25:05 AM",
        message: "Namaskar MDoNER. IWAI has 3 self-propelled barges moored at Pandu Port. We can activate river transport to Dhubri and Jogighopa at ₹850/unit with 4-day turnaround.",
        tag: "River Transport Quote",
        metrics: { price: "₹850", leadTime: "4 Days", capacity: "25k units" },
      },
      {
        id: "msg-2",
        round: 1,
        speaker: "nexus-agent",
        speakerName: "NEXUS Autonomous Inter-Agency Agent",
        avatar: "NX",
        timestamp: "10:25:22 AM",
        message: "Shri Bordoloi, we propose integrating NW-2 into the permanent MDoNER multimodal fallback charter. If IWAI mobilizes all 4 barges for continuous 24-hour night-navigation between Pandu and Dhubri, we lock a 6-month commitment at ₹620/unit.",
        tag: "Multi-Season River Charter",
        metrics: { proposedPrice: "₹620", requestedLeadTime: "2.2 Days", capacity: "35k units" },
      },
      {
        id: "msg-3",
        round: 1,
        speaker: "supplier",
        speakerName: "Pranab Bordoloi (IWAI Pandu)",
        avatar: "PB",
        timestamp: "10:25:48 AM",
        message: "Agreement confirmed. IWAI will activate night-navigational beacons along Sector 3 of the Brahmaputra. 4 barges carrying 35,000 emergency units will depart Pandu within 6 hours, arriving in Jogighopa in 2.2 days.",
        tag: "Waterway Fleet Deployed",
        metrics: { price: "₹620", leadTime: "2.2 Days", capacity: "35k units" },
      },
      {
        id: "msg-4",
        round: 1,
        speaker: "nexus-agent",
        speakerName: "NEXUS Autonomous Inter-Agency Agent",
        avatar: "NX",
        timestamp: "10:26:01 AM",
        message: "Brahmaputra river failover activated. Net transport savings: ₹0.88 Cr. Zero carbon emission penalty.",
        tag: "Round Milestone Reached",
        metrics: { status: "PROPOSAL READY", totalSavings: "₹0.88 Cr", recoveryDays: "2.2 Days" },
      },
    ],
  },
  {
    id: "sup-iaf-airbridge",
    name: "HQ Eastern Air Command & Pawan Hans Heli-Logistics",
    repName: "Group Captain Abhinav Nair",
    repRole: "Chief Operations Officer (Borjhar Air Base)",
    repAvatar: "AN",
    reliabilityScore: 99,
    historicalConsignments: 410,
    onTimeRate: 99.5,
    defectRate: 0.005,
    isoStatus: "Indian Air Force Tactical Airlift Clearance",
    initialOffer: {
      capacityUnits: 15000,
      unitPriceINR: 2800,
      baselinePriceINR: 2200,
      leadTimeDays: 1,
      rushSurchargePct: 30,
      minimumContractMonths: 1,
    },
    negotiatedOffer: {
      capacityUnits: 20000,
      unitPriceINR: 2100,
      leadTimeDays: 0.3,
      rushSurchargePct: 0,
      minimumContractMonths: 3,
      estimatedCostSavingsCr: 1.12,
    },
    dialogueRounds: [
      [
        {
          id: "msg-1",
          round: 1,
          speaker: "supplier",
          speakerName: "Gp Capt A. Nair (EAC Borjhar)",
          avatar: "AN",
          timestamp: "10:30:10 AM",
          message: "MDoNER Ops, Eastern Air Command has 2 C-130J Super Hercules on standby at Borjhar. High-priority air-lift to Lengpui (Aizawl) and Agartala costs ₹2,800/unit with immediate 24-hour launch.",
          tag: "Tactical Airlift Offer",
          metrics: { price: "₹2,800", leadTime: "24 Hours", capacity: "15k units" },
        },
        {
          id: "msg-2",
          round: 1,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Inter-Agency Agent",
          avatar: "NX",
          timestamp: "10:30:28 AM",
          message: "Group Captain, we require cryogenic oxygen tanks delivered directly to Agartala and Lengpui within 8 hours. MDoNER covers aviation fuel under NDMA Chapter IV emergency powers. Can EAC schedule 4 sorties at baseline defense rates?",
          tag: "Emergency Healthcare Air Bridge",
          metrics: { proposedLeadTime: "8 Hours", ndmaClearance: "Active" },
        },
        {
          id: "msg-3",
          round: 1,
          speaker: "supplier",
          speakerName: "Gp Capt A. Nair (EAC Borjhar)",
          avatar: "AN",
          timestamp: "10:30:52 AM",
          message: "Operation Setu Air Bridge activated! 2 C-130J and 2 Mi-17V5 helicopters will lift 20,000 units of medical oxygen and emergency rations directly to Lengpui and Agartala within 7 hours at defense rate ₹2,100/unit.",
          tag: "Sortie Cleared",
          metrics: { price: "₹2,100", leadTime: "7 Hours", capacity: "20k units" },
        },
        {
          id: "msg-4",
          round: 1,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Inter-Agency Agent",
          avatar: "NX",
          timestamp: "10:31:05 AM",
          message: "Life-critical air bridge operational. Hospital oxygen stockout completely averted. Net savings: ₹1.12 Cr.",
          tag: "Air Bridge Sealed",
          metrics: { status: "PROPOSAL READY", totalSavings: "₹1.12 Cr", recoveryDays: "0.3 Days" },
        },
      ]
    ],
    dialogueScript: [
      {
        id: "msg-1",
        round: 1,
        speaker: "supplier",
        speakerName: "Gp Capt A. Nair (EAC Borjhar)",
        avatar: "AN",
        timestamp: "10:30:10 AM",
        message: "MDoNER Ops, Eastern Air Command has 2 C-130J Super Hercules on standby at Borjhar. High-priority air-lift to Lengpui (Aizawl) and Agartala costs ₹2,800/unit with immediate 24-hour launch.",
        tag: "Tactical Airlift Offer",
        metrics: { price: "₹2,800", leadTime: "24 Hours", capacity: "15k units" },
      },
      {
        id: "msg-2",
        round: 1,
        speaker: "nexus-agent",
        speakerName: "NEXUS Autonomous Inter-Agency Agent",
        avatar: "NX",
        timestamp: "10:30:28 AM",
        message: "Group Captain, we require cryogenic oxygen tanks delivered directly to Agartala and Lengpui within 8 hours. MDoNER covers aviation fuel under NDMA Chapter IV emergency powers. Can EAC schedule 4 sorties at baseline defense rates?",
        tag: "Emergency Healthcare Air Bridge",
        metrics: { proposedLeadTime: "8 Hours", ndmaClearance: "Active" },
      },
      {
        id: "msg-3",
        round: 1,
        speaker: "supplier",
        speakerName: "Gp Capt A. Nair (EAC Borjhar)",
        avatar: "AN",
        timestamp: "10:30:52 AM",
        message: "Operation Setu Air Bridge activated! 2 C-130J and 2 Mi-17V5 helicopters will lift 20,000 units of medical oxygen and emergency rations directly to Lengpui and Agartala within 7 hours at defense rate ₹2,100/unit.",
        tag: "Sortie Cleared",
        metrics: { price: "₹2,100", leadTime: "7 Hours", capacity: "20k units" },
      },
      {
        id: "msg-4",
        round: 1,
        speaker: "nexus-agent",
        speakerName: "NEXUS Autonomous Inter-Agency Agent",
        avatar: "NX",
        timestamp: "10:31:05 AM",
        message: "Life-critical air bridge operational. Hospital oxygen stockout completely averted. Net savings: ₹1.12 Cr.",
        tag: "Air Bridge Sealed",
        metrics: { status: "PROPOSAL READY", totalSavings: "₹1.12 Cr", recoveryDays: "0.3 Days" },
      },
    ],
  },
  {
    id: "sup-iocl-logistics",
    name: "Indian Oil Corporation Ltd (North East State Office)",
    repName: "Ananya Hazarika",
    repRole: "Executive Director (Supply Chain & POL)",
    repAvatar: "AH",
    reliabilityScore: 97,
    historicalConsignments: 1100,
    onTimeRate: 98.1,
    defectRate: 0.015,
    isoStatus: "Hydrocarbon Pipeline & Tanker Safety Certified",
    initialOffer: {
      capacityUnits: 45000,
      unitPriceINR: 1350,
      baselinePriceINR: 1100,
      leadTimeDays: 4,
      rushSurchargePct: 15,
      minimumContractMonths: 3,
    },
    negotiatedOffer: {
      capacityUnits: 60000,
      unitPriceINR: 1080,
      leadTimeDays: 1.8,
      rushSurchargePct: 0,
      minimumContractMonths: 6,
      estimatedCostSavingsCr: 1.35,
    },
    dialogueRounds: [
      [
        {
          id: "msg-1",
          round: 1,
          speaker: "supplier",
          speakerName: "Ananya Hazarika (IOCL NE)",
          avatar: "AH",
          timestamp: "10:35:10 AM",
          message: "Greetings MDoNER. With Sonapur Pass blocked, 80 fuel tankers are queued. Rerouting fuel convoys via alternative Bangladesh transit (Dawki-Tamabil) or rail requires special customs bonding and ₹1,350/unit freight.",
          tag: "Emergency Fuel Rerouting Quote",
          metrics: { price: "₹1,350", leadTime: "4 Days", capacity: "45k units" },
        },
        {
          id: "msg-2",
          round: 1,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Inter-Agency Agent",
          avatar: "NX",
          timestamp: "10:35:30 AM",
          message: "Smt. Hazarika, MDoNER has coordinated expedited customs transit protocols with the Ministry of External Affairs for the Dawki-Tamabil corridor. In exchange for committing 60,000 units/month of guaranteed off-take from Numaligarh Refinery, can IOCL deploy 40 bonded tankers within 48 hours?",
          tag: "Diplomatic Transit Accord",
          metrics: { proposedPrice: "₹1,080", requestedLeadTime: "1.8 Days", volume: "60k units/mo" },
        },
        {
          id: "msg-3",
          round: 1,
          speaker: "supplier",
          speakerName: "Ananya Hazarika (IOCL NE)",
          avatar: "AH",
          timestamp: "10:35:55 AM",
          message: "Excellent. With the MEA green channel confirmed, IOCL will waive the transit surcharge, set the rate to ₹1,080/unit, and release 60,000 units of high-altitude diesel and petrol arriving in Agartala in 44 hours.",
          tag: "Fuel Accord Signed",
          metrics: { price: "₹1,080", leadTime: "1.8 Days", capacity: "60k units" },
        },
        {
          id: "msg-4",
          round: 1,
          speaker: "nexus-agent",
          speakerName: "NEXUS Autonomous Inter-Agency Agent",
          avatar: "NX",
          timestamp: "10:36:08 AM",
          message: "Critical POL fuel supply protected: Net savings ₹1.35 Cr, generator blackout in isolated hospital ICU wards averted.",
          tag: "Round 1 Milestone Reached",
          metrics: { status: "PROPOSAL READY", totalSavings: "₹1.35 Cr", recoveryDays: "1.8 Days" },
        },
      ]
    ],
    dialogueScript: [
      {
        id: "msg-1",
        round: 1,
        speaker: "supplier",
        speakerName: "Ananya Hazarika (IOCL NE)",
        avatar: "AH",
        timestamp: "10:35:10 AM",
        message: "Greetings MDoNER. With Sonapur Pass blocked, 80 fuel tankers are queued. Rerouting fuel convoys via alternative Bangladesh transit (Dawki-Tamabil) or rail requires special customs bonding and ₹1,350/unit freight.",
        tag: "Emergency Fuel Rerouting Quote",
        metrics: { price: "₹1,350", leadTime: "4 Days", capacity: "45k units" },
      },
      {
        id: "msg-2",
        round: 1,
        speaker: "nexus-agent",
        speakerName: "NEXUS Autonomous Inter-Agency Agent",
        avatar: "NX",
        timestamp: "10:35:30 AM",
        message: "Smt. Hazarika, MDoNER has coordinated expedited customs transit protocols with the Ministry of External Affairs for the Dawki-Tamabil corridor. In exchange for committing 60,000 units/month of guaranteed off-take from Numaligarh Refinery, can IOCL deploy 40 bonded tankers within 48 hours?",
        tag: "Diplomatic Transit Accord",
        metrics: { proposedPrice: "₹1,080", requestedLeadTime: "1.8 Days", volume: "60k units/mo" },
      },
      {
        id: "msg-3",
        round: 1,
        speaker: "supplier",
        speakerName: "Ananya Hazarika (IOCL NE)",
        avatar: "AH",
        timestamp: "10:35:55 AM",
        message: "Excellent. With the MEA green channel confirmed, IOCL will waive the transit surcharge, set the rate to ₹1,080/unit, and release 60,000 units of high-altitude diesel and petrol arriving in Agartala in 44 hours.",
        tag: "Fuel Accord Signed",
        metrics: { price: "₹1,080", leadTime: "1.8 Days", capacity: "60k units" },
      },
      {
        id: "msg-4",
        round: 1,
        speaker: "nexus-agent",
        speakerName: "NEXUS Autonomous Inter-Agency Agent",
        avatar: "NX",
        timestamp: "10:36:08 AM",
        message: "Critical POL fuel supply protected: Net savings ₹1.35 Cr, generator blackout in isolated hospital ICU wards averted.",
        tag: "Round 1 Milestone Reached",
        metrics: { status: "PROPOSAL READY", totalSavings: "₹1.35 Cr", recoveryDays: "1.8 Days" },
      },
    ],
  },
];

export function getSupplierNegotiation(supplierId = "sup-nfr-railway") {
  return NEGOTIATION_SUPPLIERS.find(s => s.id === supplierId) || NEGOTIATION_SUPPLIERS[0];
}
